#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompleteWeatherApp.Droid.Resource", IsApplication=true)]

namespace CompleteWeatherApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F050005
			public const int colorAccent = 2131034117;
			
			// aapt resource value: 0x7F050003
			public const int colorPrimary = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int colorPrimaryDark = 2131034116;
			
			// aapt resource value: 0x7F050002
			public const int launcher_background = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010002
			public const int add = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int bg = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cloud = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int cloudiness = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int gauge = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int humidity = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int menu = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int overlay = 2130771977;
			
			// aapt resource value: 0x7F010010
			public const int w01d = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int w01n = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int w02d = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int w02n = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int w03d = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int w03n = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int w04d = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int w04n = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int w09d = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int w09n = 2130771993;
			
			// aapt resource value: 0x7F010020
			public const int w10d = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int w10n = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int w11d = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int w11n = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int w13d = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int w13n = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int w50d = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int w50n = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int wind = 2130772008;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int sliding_tabs = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int toolbar = 2130837507;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030002
			public const int Tabbar = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040002
			public const int icon = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int icon_round = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int launcher_foreground = 2130968580;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060004
			public const int AppCompatDialogStyle = 2131099652;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int MainTheme_Base = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
